name: dart_diff_cli
description: Run Flutter/Dart commands with diff checking capabilities.
version: 0.0.2

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  args: ^2.5.0
  cli_completion: ^0.4.0
  mason_logger: ^0.2.2
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner:
  build_verify:
  build_version:
  mocktail:
  test:
executables:
  dart_diff:
