name: dart_diff_cli
description: Run Flutter/Dart commands with diff checking capabilities.
version: 0.0.3
homepage: https://github.com/ProjectAJ14/flutter_diff_action
documentation: https://github.com/ProjectAJ14/flutter_diff_action/tree/main/packages/dart_diff_cli
repository: https://github.com/ProjectAJ14/flutter_diff_action/tree/main/packages/dart_diff_cli
issue_tracker: https://github.com/ProjectAJ14/flutter_diff_action/issues

topics:
  - git
  - diff
  - cli

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  args: ^2.5.0
  cli_completion: ^0.4.0
  mason_logger: ^0.2.2
  pub_updater: ^0.4.0

dev_dependencies:
  build_runner:
  build_verify:
  build_version:
  mocktail:
  test:
executables:
  dart_diff:
  ddf: