name: Flutter Diff Action
description: |
  Run Flutter commands with diff checking capabilities.
  Supports both standard Flutter commands and Melos-based workflows.
author: ProjectAJ14
branding:
  icon: zap
  color: blue

inputs:
  command:
    description: The Flutter command to execute (e.g., flutter test, dart format)
    required: true
  use-melos:
    description: Whether to execute the command using Melos for mono-repo support
    required: false
    default: 'false'
  working-dir:
    description: The working directory to run the command from
    required: false
    default: '.'
  debug:
    description: Enable debug output for troubleshooting
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Set up dart-diff
      shell: bash
      run: dart pub global activate -sgit https://github.com/Droyder7/dart_diff  --git-ref=refactor

    - name: Run exec command
      if: ${{ inputs.use-melos == 'false' }}
      shell: bash
      run: dart_diff exec -- ${{ inputs.command }}
      working-directory: ${{ inputs.working-dir }}

    - name: Run melos command
      if: ${{ inputs.use-melos == 'true' }}
      shell: bash
      run: melos exec -- dart_diff exec -- ${{ inputs.command }}
      working-directory: ${{ inputs.working-dir }}
