name: Flutter Diff Action
description: |
  Run Flutter commands with diff checking capabilities.
  Supports both standard Flutter commands and Melos-based workflows.
author: ProjectAJ14
branding:
  icon: zap
  color: blue

inputs:
  command:
    description: The Flutter command to execute (e.g., flutter test, dart format)
    required: true
  use-melos:
    description: Whether to execute the command using Melos for mono-repo support
    required: false
    default: 'false'
  debug:
    description: Enable debug output for troubleshooting
    required: false
    default: 'false'

runs:
  using: composite
  steps:
    - name: Install yq on Windows runners
      if: runner.os == 'Windows'
      shell: bash
      run: |
        echo "Installing yq parser for Windows environment..."
        choco install yq

    - name: Configure script permissions
      shell: bash
      run: chmod +x "$GITHUB_ACTION_PATH/src/script.sh"

    - name: Execute Flutter command with diff checking
      id: flutter-diff-action
      shell: bash
      run: |
        # Execute script with determined base branch
        $GITHUB_ACTION_PATH/src/script.sh \
          -n '${{ inputs.command }}' \
          -f '${{ inputs.use-melos }}' \
          ${{ inputs.debug == 'true' && '-p' || '' }}
      env:
        BASE_BRANCH: ${{ github.event_name == 'pull_request' && format('origin/{0}', github.base_ref) || 'origin/main' }}