name: flutter_diff_action
description: |
  Run Flutter/Dart commands with diff checking capabilities.
  Supports both standard Flutter commands and Melos-based workflows.
publish_to: none

environment:
  sdk: ^3.6.0

workspace:
  - packages/dart_diff_cli

dev_dependencies:
  lints: ^5.1.1
  mason_logger: ^0.3.2
  melos: ^7.8.2
  pubspec_parse: ^1.5.0

melos:
  command:
    version:
      workspaceChangelog: false
      fetchTags: true
      updateGitTagRefs: false
      linkToCommits: false
      hooks:
        post: melos run update_cli_version

  scripts:
    lint: dart format --set-exit-if-changed packages tools && dart analyze --fatal-infos
    update_cli_version:
      run: dart run tools/update_cli_version.dart
