name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master

  test_action:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - working-directory: 'example/simple_app'
            melos: false
            command: 'flutter test --no-pub --coverage'
          - working-directory: 'example/simple_app'
            melos: false
            command: 'flutter test'
          - working-directory: 'example/simple_app'
            melos: false
            command: 'flutter analyze --fatal-infos'
          - working-directory: 'example/simple_app'
            melos: false
            command: 'flutter analyze'
          - working-directory: 'example/simple_app'
            melos: false
            command: 'dart format --set-exit-if-changed'
          - working-directory: 'example/simple_app'
            melos: false
            command: 'dart format'
          - working-directory: 'example/super_app'
            melos: true
            command: 'flutter test --no-pub --coverage'
          - working-directory: 'example/super_app'
            melos: true
            command: 'flutter test'
          - working-directory: 'example/super_app'
            melos: true
            command: 'flutter analyze --fatal-infos'
          - working-directory: 'example/super_app'
            melos: true
            command: 'flutter analyze'
          - working-directory: 'example/super_app'
            melos: true
            command: 'dart format --set-exit-if-changed'
          - working-directory: 'example/super_app'
            melos: true
            command: 'dart format'
    name: |
      Test ${{ matrix.command }} (Melos: ${{ matrix.melos }})
    defaults:
      run:
        working-directory: ${{ matrix.working-directory }}
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.0'
          channel: 'stable'

      - name: Install Melos
        if: matrix.melos == true
        run: dart pub global activate melos

      - name: Run Flutter Diff Action
        uses: ./
        with:
          command: ${{ matrix.command }}
          use-melos: ${{ matrix.melos }}
          debug: true