name: test

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main
jobs:
  lint_shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master

  test_action:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.19.6
          channel: stable
          cache: true
      - name: Set up dart-diff
        run: dart pub global activate -sgit https://github.com/Droyder7/dart-diff
      - name: Change Directory
        run: cd example
      - name: Dart Format
        run: dart_diff format
      - name: Dart Analyze
        run: dart_diff analyze
      - name: Run Flutter test
        run: dart_diff test -f
